apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myapp-rollout
spec:
  replicas: 5 
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  selector:
    matchLabels:
      app: myapp-rollout
  template:
    metadata:
      labels:
        app: myapp-rollout
    spec:
      containers:
        - name: myapp-rollout
          image: ankitrajxd/myapp:1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-rollout-service
spec:
  selector:
    app: myapp-rollout
  ports:
    - protocol: TCP
      port: 30003
      targetPort: 80
  type: NodePort
---